version: "3.3"

services:
  mysql:
    image: mysql:5.6
    environment:
      MYSQL_DATABASE: isucari
      MYSQL_USER: isucari
      MYSQL_PASSWORD: isucari
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3309:3306"
    volumes:
      - test_isu_volume:/var/lib/mysql
    container_name: isu_mysql

volumes:
  test_isu_volume:
    external: true